const withImages = require('next-images');

const nextConfig = {
	env: {
		FIREBASE_API_KEY: process.env.FIREBASE_API_KEY,
		FIREBASE_AUTH_DOMAIN: process.env.FIREBASE_AUTH_DOMAIN,
		FIREBASE_DATABASE_URL: process.env.FIREBASE_DATABASE_URL,
		FIREBASE_PROJECT_ID: process.env.FIREBASE_PROJECT_ID,
		FIREBASE_STORAGE_BUCKET: process.env.FIREBASE_STORAGE_BUCKET,
		FIREBASE_MESSAGING_SENDER_ID: process.env.FIREBASE_MESSAGING_SENDER_ID,
		FIREBASE_APP_ID: process.env.FIREBASE_APP_ID,
		FIREBASE_MEASUREMENT_ID: process.env.FIREBASE_MEASUREMENT_ID,
		FIREBASE_FUNCTIONS_EMULATOR_URL: process.env.FIREBASE_FUNCTIONS_EMULATOR_URL,
		ALGOLIA_APP_ID: process.env.ALGOLIA_APP_ID,
		ALGOLIA_SEARCH_ID: process.env.ALGOLIA_SEARCH_ID,
		ENV: process.env.ENV,
	},
};
module.exports = withImages(nextConfig);
